spring:
  application:
    name: TaskApplication
  datasource:
    url: "jdbc:h2:mem:test_database"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "sa"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "972548040454-2vj1a53o7b3ujoaf67noi20q6rim7am2.apps.googleusercontent.com"
            client-secret: "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"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect


server:
  tomcat:
    relaxed-path-chars: <,>,[,\,\,],^,`,{,|


management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        sla:
          http:
            server:
              requests: true