spring:
  application:
    name: TaskApplication
  datasource:
    url: "jdbc:h2:mem:test_database"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


